### ISSUE TITLE
gzip disabled and "No threading detected. Own threads" in error.log

### ISSUE THREAD

**Issue by Veiote** [ldkafka/ngx_pagespeed#1]
Hi !

my nginx error.log is growing a lot with these messages:

... pagespeed: rollback gzip, explicit configuration in /etc/nginx/nginx.conf:71
... [ngx_pagespeed 1.13.35.2-0] No threading detected. Own threads: 1 Rewrite, 1 Expensive Rewrite.

Are u getting too?

Thx

**Comment by ldkafka** [comment]
Hi,

Both those messages seem to be common and present in pagespeed installations at large (not specific to this compiled version) - if you do a Google search you will see many discussion threads about them. I get them as well, and I believe they are not an issue.

Luci
